/* **********************************
-- Session #1 で実行
************************************ */
DROP INDEX IF EXISTS NCIX_L_ORDERKEY ON LINEITEM
CREATE INDEX NCIX_L_ORDERKEY ON LINEITEM (L_ORDERKEY)
GO
DBCC FREEPROCCACHE
GO
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
BEGIN TRAN
SELECT　L_ORDERKEY FROM LINEITEM WITH(XLOCK) WHERE L_ORDERKEY = 100
-- COMMIT TRAN

/* **********************************
Sesion #2 で実行
************************************ */
USE [tpch]
GO
SELECT L_RETURNFLAG, L_LINESTATUS, SUM(L_QUANTITY) AS SUM_QTY,
 SUM(L_EXTENDEDPRICE) AS SUM_BASE_PRICE, SUM(L_EXTENDEDPRICE*(1-L_DISCOUNT)) AS SUM_DISC_PRICE,
 SUM(L_EXTENDEDPRICE*(1-L_DISCOUNT)*(1+L_TAX)) AS SUM_CHARGE, AVG(L_QUANTITY) AS AVG_QTY,
 AVG(L_EXTENDEDPRICE) AS AVG_PRICE, AVG(L_DISCOUNT) AS AVG_DISC, COUNT(*) AS COUNT_ORDER
FROM LINEITEM
WHERE L_SHIPDATE <= dateadd(dd, -90, cast('1998-12-01' as datetime))
GROUP BY L_RETURNFLAG, L_LINESTATUS
ORDER BY L_RETURNFLAG,L_LINESTATUS
GO
